### ISSUE TITLE
hourglass

### ISSUE THREAD

**Issue by onkelyoo** [FortAwesome/font-awesome-sass#102]
Hello,

it seems that the hourglasses are missing. If I implement them they are not showing up. 
<i class="fa fa-hourglass-half"></i>
<i class="fa fa-hourglass-start"></i>
<i class="fa fa-hourglass-end"></i>

Kind Regards!
Daniel

**Comment by andreykul** [comment]
Cannot Replicate. Hourglass icons work fine.
