### ISSUE TITLE
birthday-cake is not working

### ISSUE THREAD

**Issue by krtschmr** [FortAwesome/font-awesome-sass#103]
fa-birthday-cake is not working. using calendar instead.

all others are doing fine

V 4.4.0

anyone else?

**Comment by andreykul** [comment]
icon 'birthday-cake'

<img width="22" alt="screen shot 2015-11-02 at 8 36 50 am" src="https://cloud.githubusercontent.com/assets/2347787/10881888/eef9f874-813c-11e5-8d08-7821105a0109.png">

works fine.
