### ISSUE TITLE
Rails 5 issue

### ISSUE THREAD

**Issue by alejandrodevs** [FortAwesome/font-awesome-sass#114]
I'm getting this when I start rails server (rails5.0.0.beta3):

`undefined method 'start_with?' for /font-awesome\/fontawesome-webfont\.(?:eot|svg|ttf|woff|woff2?)$/:Regexp`

**Comment by maartenvanvliet** [comment]
Caused by this issue: https://github.com/rails/sprockets-rails/issues/269

Sprockets no longer accepts regexes

**Comment by kugaevsky** [comment]
@alejandrodevs you can use my PR to fix it.

**Comment by supercodepoet** [comment]
Should be fixed in the latest 4.6.1 just pushed
