### ISSUE TITLE
Fontawesome Pro, Turbolinks and the new (and shiny) SVG with JavaScript

### ISSUE THREAD

**Issue by richjdsmith** [FortAwesome/font-awesome-sass#149]
Can we expect to see a solution to using the new SVG with JavaScript and FontAwesome Pro without it breaking Turbolinks?

Heck, even just pro would be fantastic.

Cheers!

**Comment by robmadole** [comment]
@richjdsmith this is the wrong repository for reporting on SVG with JS (this is the `font-awesome-sass`) project and it uses web fonts.

Here is the general issue: https://github.com/FortAwesome/Font-Awesome/issues/11924
