### ISSUE TITLE
Required version bump

### ISSUE THREAD

**Issue by kstratis** [FortAwesome/font-awesome-sass#160]
Since FontAwesome is now a mature project, this needs to be updated to the latest version which at the time of writing is 5.2.

**Comment by kimpastro** [comment]
They've added 372 Icons in Version 5.2.0.
https://blog.fontawesome.com/font-awesome-5-2-372-new-icons-adfb42c6c35

**Comment by supercodepoet** [comment]
This gem has now been updated to Font Awesome Free 5.2.0
