### ISSUE TITLE
How to rebuild fa-spin to control how it works?

### ISSUE THREAD

**Issue by o-alquimista** [FortAwesome/font-awesome-sass#191]
What if I want an icon to only spin when it's hovered, without using JavaScript, and using the `fa-spin` class?

I was thinking maybe I could use your mixins to rebuild the `fa-spin` class my way, but I'm not sure how to make it work for `fa-spin`. Is it the same as any other icon class?

**Comment by robmadole** [comment]
@o-alquimista your best bet would be to write your own CSS and use the `:hover` element state. The CSS for `fa-spin` is pretty straight-forward and easy enough to copy.
