### ISSUE TITLE
no git tag for 5.13.0 so file-diff is not appeared at dependabot

### ISSUE THREAD

**Issue by suzuki-srj** [FortAwesome/font-awesome-sass#194]
today, I realized that. 
maybe the reason is that there is no tag for `5.13.0`

**Comment by suzuki-srj** [comment]
the link for `compare view` is https://github.com/FortAwesome/font-awesome-sass/commits
<img width="943" alt="スクリーンショット 2020-05-29 12 29 31" src="https://user-images.githubusercontent.com/63273158/83218027-0e9d7800-a1a8-11ea-99fb-787b28fc6833.png">

**Comment by supercodepoet** [comment]
thanks, forgot to tag. That should be fixed now.

**Comment by suzuki-srj** [comment]
thanks! 😄  👍
