### ISSUE TITLE
Error: Can't find stylesheet to import. in rails 7

### ISSUE THREAD

**Issue by adeetyak** [FortAwesome/font-awesome-sass#203]
I am using rails 7 . After running bundle install on mentioning the gem, I mentioned @import "font-awesome";
@import "font-awesome-sprockets"; in application.scss.css . When I run ./bin/dev , an error populates Error: Can't find stylesheet to import. Kindly, suggest the best way.

**Comment by supercodepoet** [comment]
I have removed `font-awesome-sprockets` as it was no longer needed. I used SASS functions to accomplish the same goal. All you need to do now is:

```scss
@import font-awesome;
```

**Comment by ReazerDev** [comment]
Can confirm, I have the same issue. I tried replacing sass-rails with cssbundling-rails, as I'm also using jsbundling-rails, and after install cssbundling, it can't find "font-awesome".

I presume it's needed to add another load-path to the build:sass script, but I don't know what I should put there.

**Comment by caioertai** [comment]
I've managed to make it work by importing it via JS. Here's what I followed:
https://blog.corsego.com/fontawesome-importmaps-rails7

**Comment by lukas-conlance** [comment]
👍 
@caioertai I continued with `propshaft` and `jsbundling-rails` (with esbuild) which works quite well.
