### ISSUE TITLE
Bower?

### ISSUE THREAD

**Issue by theaqua** [FortAwesome/font-awesome-sass#22]
Hello, can you add this repo to bower registry?

**Comment by olliebennett** [comment]
There's a `bower.json` in the [FortAwesome/Font-Awesome](https://github.com/FortAwesome/Font-Awesome) repository, which includes the SCSS (or LESS) and can be used with any other project.

Am sure that would solve the problem for @theaqua and @juliotaylor and we can close this issue?

**Comment by theaqua** [comment]
Oh, right.
