### ISSUE TITLE
`@import` is deprecated

### ISSUE THREAD

**Issue by mikevoets** [FortAwesome/font-awesome-sass#237]
When we use this library and compile it with dartsass, it logs the following deprecation warnings:

```
| DEPRECATION WARNING: Sass @import rules are deprecated and will be removed in Dart Sass 3.0.0.
|
| More info and automated migrator: https://sass-lang.com/d/import
|
|   ╷
| 9 │ @import "font-awesome/functions";
|   │         ^^^^^^^^^^^^^^^^^^^^^^^^
|   ╵
|     _font-awesome.scss 9:9                    @use
|     app/assets/stylesheets/accounts.scss 1:1  root stylesheet
|
```

This happens because `@import` has been marked as deprecated since dartsass 1.80.0 (https://sass-lang.com/blog/import-is-deprecated/).

**Comment by robmadole** [comment]
We won't be able to fix this in Font Awesome 6. Our recommendation is to silence the warning. 😬
