### ISSUE TITLE
fa-university, fa-bank, fa-institution not working

### ISSUE THREAD

**Issue by DaveBagler** [FortAwesome/font-awesome-sass#41]
I'm using font-awesome-sass as part of a compass project (I'm also using bootstrap-sass).

The fa-university icon (and it's aliases) do not show up.  My first thought was that it was a 4.1 vs 4.0 issue but all the other 4.1 icons appear to be working.

The CSS does include the <code>.fa-university</code> class and the CSS is appearing when I inspect the :before sudo element of the <code>&lt;i&gt;</code> tag.  So it seems like the <code>\f19c</code> character is not in the font.

**Comment by gabrlknght** [comment]
I'm having this exact same issue w/ the latest version of the Drupal FontAwesome module, which does include fonts/references in css to the same fa-university, fa-bank, and fa-institution classes. These are not coming up for me at all via Chrome/Safari/Firefox for Mac no matter what I've tried....

**Comment by supercodepoet** [comment]
Here are some screen grabs using the new 4.3.0 gem. Re-open the ticket if this is still a problem.

![screen shot 2015-01-31 at 5 02 09 pm](https://cloud.githubusercontent.com/assets/249366/5990001/04082e52-a96b-11e4-87b6-afdcd220fffc.png)
![screen shot 2015-01-31 at 5 02 15 pm](https://cloud.githubusercontent.com/assets/249366/5990002/0713435c-a96b-11e4-8a6f-cef65fe17f1d.png)

**Comment by miqmago** [comment]
Not working in 4.6.3 Chrome, Firefox, Safari Mac OSX

**Comment by nop1984** [comment]
not working also
