### ISSUE TITLE
Rotated & Flipped icons are broken

### ISSUE THREAD

**Issue by cspeer** [FortAwesome/font-awesome-sass#66]
Hi,

in the latest version of font-awesome the rotated & flipped styles are broken.
http://fortawesome.github.io/Font-Awesome/examples/#rotated-flipped
Only the "normal" example is shown.
Unfortunately this has made its way into this awesome gem.

Cheers

//Edit: I forgot to mention that it's a problem in the latest Chrome Canary only

**Comment by supercodepoet** [comment]
I just took a look in Canary and it seems to be working. Do you still experience this issue?

![screen shot 2015-01-31 at 3 47 47 pm](https://cloud.githubusercontent.com/assets/249366/5989772/8bc20c1a-a960-11e4-903f-811004a1a422.png)

**Comment by cspeer** [comment]
Works perfectly :+1: Thanks
