### ISSUE TITLE
uninitialized constant FontAwesome::Sass::VERSION

### ISSUE THREAD

**Issue by zedtux** [FortAwesome/font-awesome-sass#73]
I have upgraded the gem from version 4.2.2 to the version 4.3.0 and I'm facing this error now:

    /usr/local/lib/ruby/gems/2.2.0/gems/font-awesome-sass-4.3.0/lib/font-awesome-sass.rb:57:in `register_compass_extension': uninitialized constant FontAwesome::Sass::VERSION (NameError)
      from /usr/local/lib/ruby/gems/2.2.0/gems/font-awesome-sass-4.3.0/lib/font-awesome-sass.rb:5:in `load!'
      from /usr/local/lib/ruby/gems/2.2.0/gems/font-awesome-sass-4.3.0/lib/font-awesome-sass.rb:79:in `<top (required)>'
      from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.7.12/lib/bundler/runtime.rb:76:in `require'
      from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.7.12/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
      from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.7.12/lib/bundler/runtime.rb:72:in `each'
      from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.7.12/lib/bundler/runtime.rb:72:in `block in require'
      from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.7.12/lib/bundler/runtime.rb:61:in `each'
      from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.7.12/lib/bundler/runtime.rb:61:in `require'
      from /usr/loc
      from /application/spec/rails_helper.rb:4:in `require'
      from /application/spec/rails_helper.rb:4:in `<top (required)>'
      from /application/spec/controllers/admin/schools_controller_spec.rb:1:in `require'
      from /application/spec/controllers/admin/schools_controller_spec.rb:1:in `<top (required)>'
      from /usr/local/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.0/lib/rspec/core/configuration.rb:1226:in `load'
      from /usr/local/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.0/lib/rspec/core/configuration.rb:1226:in `block in load_spec_files'
      from /usr/local/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.0/lib/rspec/core/configuration.rb:1224:in `each'
      from /usr/local/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.0/lib/rspec/core/configuration.rb:1224:in `load_spec_files'
      from /usr/local/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.0/lib/rspec/core/runner.rb:97:in `setup'
      from /usr/local/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.0/lib/rspec/core/runner.rb:85:in `run'
      from /usr/local/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.0/lib/rspec/core/runner.rb:70:in `run'
      from /usr/local/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.0/lib/rspec/core/runner.rb:38:in `invoke'
      from /usr/local/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.0/exe/rspec:4:in `<top (required)>'
      from /usr/local/bin/rspec:23:in `load'
      from /usr/local/bin/rspec:23:in `<main>'

**Comment by zedtux** [comment]
Downgrading to version 4.2.2 solved the issue.

**Comment by supercodepoet** [comment]
Sorry for the goof. Please try 4.3.1 for the fix
