### ISSUE TITLE
SemVer please?

### ISSUE THREAD

**Issue by botandrose** [FortAwesome/font-awesome-sass#74]
4.2.2 -> 4.3.0 is not a backwards-compatible upgrade, e.g. #73. May I suggest considering adopting semantic versioning for future releases?

http://semver.org/

**Comment by supercodepoet** [comment]
Update 4.3.1 to include a reference to the version file.

**Comment by botandrose** [comment]
Ah, it was just a bug. Thanks for the quick fix.

I do want to reiterate my desire for for semver, though. 4.1 -> 4.2 broke imports with the new requirement to `@import "font-awesome-sprockets";` before `@import "font-awesome";`, IIRC.

In any event, thanks for `font-awesome-sass`!
