### ISSUE TITLE
Using withruby sass

### ISSUE THREAD

**Issue by vko-online** [FortAwesome/font-awesome-sass#77]
I would like to install it in existing project.
`gem install font-awesome-sass` - downloaded and installed gem in system
But how to i add this sass files to project?
In bourbon you could do this 
`gem install bourbon` then go to project folder where you want to install it, `bourbon install` and files will be there

**Comment by olliebennett** [comment]
Hi @vko-online, what kind of project is your "existing project"? Rails and Compass usage are both described in the [README](https://github.com/FortAwesome/font-awesome-sass/blob/master/README.md).

Did you forget to call `@import` on the SCSS files? If using Compass, did you add `require 'font-awesome-sass'` in your `config.rb` file?

If you've resolved this issue, or still have problems, would you care to explain and/or close the issue?
