### ISSUE TITLE
Update to FontAwesome 4.4.0

### ISSUE THREAD

**Issue by Tibfib** [FortAwesome/font-awesome-sass#96]
https://github.com/FortAwesome/Font-Awesome/releases/tag/v4.4.0

**Comment by ramaboo** [comment]
+100

**Comment by XmlmXmlmX** [comment]
+100

**Comment by jdenquin** [comment]
+10000

**Comment by carlosbutler** [comment]
+1-gazillion

**Comment by shlima** [comment]
+1

**Comment by adrianscott83** [comment]
+1

**Comment by Tuckie** [comment]
+0

**Comment by miguxbe** [comment]
+01

**Comment by opensourceame** [comment]
+1

**Comment by campreb** [comment]
:+1:

**Comment by vadim-zverugo** [comment]
+1

**Comment by net** [comment]
+1

**Comment by dan** [comment]
🙏🙇

**Comment by kkirsche** [comment]
+1

**Comment by the-ult** [comment]
+1

**Comment by eveevans** [comment]
+1

**Comment by supercodepoet** [comment]
Sorry for the delay. May need to seek help with this gem as I have been slammed recently. This is now pushed to RubyGems. Please check it out and make sure it works for all of you. I tested it on Rails 4.0, 4.1, and 4.2. I do not use Compass so if anyone wants to send me a test project I can use to test the gem that would be awesome.

**Comment by kkirsche** [comment]
@supercodepoet what's involved in updates? Is it just merging a branch to keep parity with `font-awesome`'s main repo? Want to make sure I understand it, but may be able to help out if interested
